# Generated by Django 5.0.2 on 2024-03-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatistic',
            old_name='max_value',
            new_name='max_dialogues',
        ),
        migrations.RemoveField(
            model_name='userstatistic',
            name='min_value',
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='current_dialogues',
            field=models.IntegerField(default=0),
        ),
    ]
