# Generated by Django 5.0.2 on 2024-03-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_rename_max_value_userstatistic_max_dialogues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tariff',
            field=models.CharField(choices=[('Basic', 'Базовый'), ('Professional', 'Профессиональный'), ('Premium', 'Премиум'), ('Startup', 'Стартап'), ('Corporate', 'Корпоративный')], default='Basic', max_length=120),
        ),
    ]
