# Generated by Django 5.0.2 on 2024-03-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_user_tariff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatistic',
            old_name='type',
            new_name='model_id',
        ),
    ]
